### ISSUE TITLE
first simple workflow fails START_TO_CLOSE timeout, 

### ISSUE THREAD

**Issue by chamarts** [uber-go/cadence-client#1220]
**Describe the bug**
created simple workflow and it throws an error while fetching the result. appreciate any quick help 

Result 
{
  "timeoutType": "START_TO_CLOSE"
}. Tried debugging until RPCRetrier.retryWithResult but not successful. 

workflow interface 
@WorkflowMethod(executionStartToCloseTimeoutSeconds = 10, taskList = TASK_LIST )
String doTheRightThing(); 

**To Reproduce**
Is the issue reproducible? 
- Yes

**Steps to reproduce the behavior:**
A clear and concise description of the reproduce steps.

**Expected behavior**
Should return result "SUCCESS" and history should show workflow completed with return result "SUCCESS"

**Screenshots**

**Additional context**
stacktrace 
	at com.uber.cadence.internal.common.WorkflowExecutionUtils.getResultFromCloseEvent(WorkflowExecutionUtils.java:166)
	at com.uber.cadence.internal.common.WorkflowExecutionUtils.getWorkflowExecutionResult(WorkflowExecutionUtils.java:121)
	at com.uber.cadence.internal.sync.WorkflowStubImpl.getResult(WorkflowStubImpl.java:307)
	at com.uber.cadence.internal.sync.WorkflowStubImpl.getResult(WorkflowStubImpl.java:289)
	at com.uber.cadence.internal.sync.WorkflowInvocationHandler$SyncWorkflowInvocationHandler.startWorkflow(WorkflowInvocationHandler.java:289)
	at com.uber.cadence.internal.sync.WorkflowInvocationHandler$SyncWorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:248)
	at com.uber.cadence.internal.sync.WorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:164)

**Comment by ibarrajo** [comment]
Did you try a larger timeout? If the execution takes longer than the start to close timeout you would get this error.
