### ISSUE TITLE
Non deterministic error causing the worker to crash

### ISSUE THREAD

**Issue by samarabbas** [uber-go/cadence-client#332]
Running the following workflow will cause panic in worker and cause it to crash:

```
func Workflow(ctx workflow.Context, name string) error {
	ao := workflow.ActivityOptions{
		ScheduleToStartTimeout: time.Minute,
		StartToCloseTimeout:    time.Minute,
		HeartbeatTimeout:       time.Second * 20,
	}
	ctx = workflow.WithActivityOptions(ctx, ao)

	logger := workflow.GetLogger(ctx)
	logger.Info("helloworld workflow started")

	if counter == 0 {
		counter++
		workflow.ExecuteActivity(ctx, helloworldActivity, name)
	}

	logger.Info("Cadence.Sleep", zap.Int("Sleep", 5), zap.Int("Counter", counter))
	workflow.Sleep(ctx, 10 * time.Second)

	logger.Info("Woke up", zap.Int("Counter", counter))
	if counter == 1 {
		counter++
		logger.Info("Panic.", zap.Int("Counter", counter))
		panic("Cause Replay!!!")
	}

	logger.Info("Completing Workflow", zap.Int("Counter", counter))
	logger.Info("Workflow completed.")

	return nil
}
```

Here is the call-stack:
```
panic: unknown decision DecisionType: Activity, ID: 0, possible causes are nondeterministic workflow definition code or incompatible change in the workflow definition

goroutine 76 [running]:
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*decisionsHelper).getDecision(0xc42057f350, 0xc400000000, 0xc4203b81f0, 0x1, 0xc4204922a0, 0x1)
	code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_decision_state_machine.go:611 +0x197
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*decisionsHelper).handleActivityTaskScheduled(0xc42057f350, 0x5, 0xc4203b81f0, 0x1)
	code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_decision_state_machine.go:642 +0x89
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*workflowExecutionEventHandlerImpl).ProcessEvent(0xc4203b0680, 0xc420767ce0, 0x1, 0x0, 0x0, 0xc42057a090, 0x0, 0x1)
	code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_event_handlers.go:469 +0x513
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*workflowTaskHandlerImpl).ProcessWorkflowTask(0xc42059b380, 0xc4201c5a40, 0x22e7480, 0xc420571380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_task_handlers.go:625 +0x69c
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*workflowTaskPoller).ProcessTask(0xc4205b4f00, 0x19db5c0, 0xc42057f260, 0x2e532073696c6174, 0x3333302f2e412e70)
	code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_task_pollers.go:177 +0xc1
code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*baseWorker).processTask(0xc42035a300, 0x19db5c0, 0xc42057f260)
	code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_worker_base.go:249 +0x66
created by code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal.(*baseWorker).runTaskDispatcher
	code.uber.internal/devexp/cadence-samples.git/vendor/go.uber.org/cadence/internal/internal_worker_base.go:220 +0xd9
```

**Comment by yiminc** [comment]
fixed
